prop1: "value1"
prop2: "value2"
user:
  role: Developer api gateway from docker profile

spring:
  cloud:
    consul:
      discovery:
        register: true  # Register service to Consul
        deregister: true # Deregister when shutting down
        service-name: gateway-service
        tags:
          - "Gateway"
      host: consul
      port: 8500
      config:
        enabled: false