
prop1: "value1"
prop2: "value2"
user:
  role: Developer api gateway from development profile

spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        register-health-check: true
        tags:
          - "Gateway"
      host: localhost
      port: 8500
      config:
        enabled: false